### ISSUE TITLE
Can't get offset.

### ISSUE THREAD

**Issue by joetemp** [thomasvs/morituri#103]
I used the reference list and found what I thought was my correct drive and set offset to 79. Didn't work. When I try to use morituri to find my offset... it just tries a bunch of numbers, seemingly arbitrarily and just keeps going. Never finds the correct number. What's going on here? Clearly I've missed something.

**Comment by ArchangeGabriel** [comment]
What CD did you use for this? I had this problem too, because I use a quite unknown one (from a little french metal band), and then tried with a Deep Purple one and it worked.

You indeed need a very known CD for morituri to be able to compare the ripped track hash with the DB. Also, 79 is a bit far in the list (https://github.com/thomasvs/morituri/blob/master/morituri/rip/offset.py#L37), so you would need to let it run a long time before morituri finding it, I suggest you to run `rip offset find -o +79` once you’ve inserted a popular CD.

**Comment by joetemp** [comment]
Thanks! I took that advice to try and find the offset and it totally worked!
