### ISSUE TITLE
What should I make of confidence?

### ISSUE THREAD

**Issue by joetemp** [thomasvs/morituri#104]
So, when I'm done ripping an album, I get my confidence ratings... which seem to be arbitrary since I can't make any sense of the numbering scheme. I would think it would be out of 100 but it will say confidence is 25 of 200. Or 65 of 109. I don't understand. Should I just assume that if it says each rip is accurate that it is? Also, I had one track say "max confidence" but it also said that the rip was "NOT accurate". What am I to make of all this? Thanks!

**Comment by joetemp** [comment]
Along these same lines... ripped an album today and the first song has a peak level of 38.65%. I've never seen anything below 90. What should I make of that?

**Comment by thomasvs** [comment]
On 01/18/2015 12:55 AM, Joe Templeton wrote:
>
> Along these same lines... ripped an album today and the first song has 
> a peak level of 38.65%. I've never seen anything below 90. What should 
> I make of that?
>

I'm surprised you've never seen anything below 90.  Remember that going 
from 100% to 50% in peak level is only a 6dB drop.  CD's have a dynamic 
range of 96dB.  It would be fairly common for an intro track to have a 
lower peak level.

What album is this?

Thomas

> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thomasvs/morituri/issues/104#issuecomment-70397614>.
>


-- 

If you go
go for good
don't fucking joke
you know I would

MOAP - Maintaining your projects since 2006
https://apestaart.org/moap/trac/

**Comment by thomasvs** [comment]
It's directly based on EAC's output, and I agree it's not 100% intuitive.

Yes, it does look like the AccurateRip database maxes out at 200 
submissions.  You would have to ask the guy running it why that is.

When it says confidence is 25 out of 200, that means that in the pool of 
200 submissions accuraterip has for this disc, 25 match your checksum.  
It's fairly common to have different pressings with the same disc id but 
slightly different audio data, resulting in different checksums.  
Sometimes it's also simply because of submissions with wrong offsets, 
but less likely.

Can you cut and paste the line that says max confidence but not accurate?

T

On 01/13/2015 11:10 PM, Joe Templeton wrote:
>
> So, when I'm done ripping an album, I get my confidence ratings... 
> which seem to be arbitrary since I can't make any sense of the 
> numbering scheme. I would think it would be out of 100 but it will say 
> confidence is 25 of 200. Or 65 of 109. I don't understand. Should I 
> just assume that if it says each rip is accurate that it is? Also, I 
> had one track say "max confidence" but it also said that the rip was 
> "NOT accurate". What am I to make of all this? Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thomasvs/morituri/issues/104>.
>



-- 

I hear that she likes to dance around the room
to a wornout twelve inch of Marquee Moon

URGent, best radio on the net - 24/7 !
http://urgent.fm/

**Comment by joetemp** [comment]
All this makes total sense. I understand it all now. Thanks!
