### ISSUE TITLE
doesn't write out .log files (etc.) if there's trouble with a track

### ISSUE THREAD

**Issue by jmtd** [thomasvs/morituri#113]
`morituri` just ripped 13/15 tracks of a CD, but it gave up on track 14 after a few tries. As a result, it didn't write out the cue/log/m3u files for the tracks it did rip.

**Comment by thomasvs** [comment]
Correct, that is by design.  morituri is made to do accurate rips of full albums, or give up if that's impossible.

There are plenty of ripping applications out there that are fine doing inaccurate rips.

**Comment by jmtd** [comment]
I understand morituri's mission statement: it's why I'm using (and hopefully shortly contributing to) morituri :) however, it *successfully* ripped tracks 1-13, but because it didn't write out the log file, I don't have a convenient record of it doing so, nor of it correctly verifying the checksums against accurate rip. Should I toss out tracks 1-13 because it had trouble with track 14? Or go and rip them with something else, and have less confidence, because I couldn't get the whole CD? (likewise I guess with issue #114, if morituri could successfully and confidently rip track 15, should it not try, even if track 14 didn't work out?)

I think it should still write out a log, including detailing the problems with track 14, and attempt track 15. It should probably still return an error code to the shell. (it should probably still eject the CD).

**Comment by ArchangeGabriel** [comment]
Hum, I don’t agree with all of it, but I think that an option to do that would be nice, in case for instance you have a damaged CD, but would like to get the most of it, and that the more accurately possible.

**Comment by mikehat** [comment]
To demand perfection of the entire disc, why move anything from the working directory at all until full success is achieved. It's just random and rude to halt the rip on one bad track.

Best would be a command line option to abandon the track, like `--ignore-track 7`. This would ensure intent to ignore on the behalf of the user rather than some sort of blanket approval.

Sure, I'll rip the bad one with wine/EAC, but will get inferior meta tags and file naming, not to mention having to use a mouse. Yuck.

Rather than submit a pull request that'll never be accepted, here's the fix for those that are interested:

In the source directory, edit `morituri/rip/cp.py`. Look in the `ripIfNotRipped` function, look for

    if tries == MAX_TRIES
        self.error( 'Giving up on track...

and change `self.error` to `self.stdout.write`. Something like:

        self.stdout.write( `Giving up on track %d after %d tries\n\n\n\nOMG A TRACK FAILED/n/n/n' %
            ( number , tries )

That should get your attention when one fails.

Do yourself another favor and look at the top of the file for `MAX_TRIES=5` and change it to `MAX_TRIES=2` so you can get back to work more quickly.
