### ISSUE TITLE
No MusicBrainz data on very popular album.

### ISSUE THREAD

**Issue by joetemp** [thomasvs/morituri#124]
Morituri is giving me an error, saying that music data cannot be found and that I need to submit the album to MusicBrainz. The problem is... there already is music data for this album:

https://musicbrainz.org/release/a40fc6ad-9ec3-4a61-abee-79f06f82f642

That's just one entry of many. So, is this a problem with Morituri? Is there a way to force the rip and edit tags later? What should I do here?

**Comment by joetemp** [comment]
Never mind. After like 5 tries, it somehow worked. Thanks!

**Comment by thomasvs** [comment]
The link you gave was linking to an mp3 version of the release, so that would not have been the right one.

The thing you could have done was to follow the link, and then attach this disc id to the right release (the matching cd one, not the mp3 one) I assume someone did that in the meantime which caused it to work for you.  Glad it worked!
